(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DEFAULTS={maintenance_mode:false,maintenance_message:'The grimoire is undergoing restoration.',announcement:'',tarot_enabled:true,sigils_enabled:true,book_enabled:true,academy_enabled:true,profiles_enabled:true,inbox_enabled:true};
const get=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let settings={...DEFAULTS,...get('veiledLocalSettings',{})};
let profile={display_name:get('veiledLocalProfile',{}).display_name||'VEILED Seeker',role:'owner',status:'active',...get('veiledLocalProfile',{})};
function saveProfile(){set('veiledLocalProfile',profile)}
function saveSettings(){set('veiledLocalSettings',settings)}
function gateOpened(){return localStorage.getItem('veiledEntered')==='true'||$('#veilGate')?.classList.contains('hidden')}
function showSite(){if(settings.maintenance_mode&&profile.role!=='owner'){return}$('#site')?.classList.remove('hidden');addAccountChip();applyFlags();buildOwnerPanel();}
function addAccountChip(){if($('#accountChip'))return;$('.top-tools')?.insertAdjacentHTML('beforeend',`<button id="accountChip" class="account-chip"><span class="cloud-sync-dot"></span>${esc(profile.display_name)}</button>`);$('#accountChip').onclick=openAccount}
function openAccount(){const m=$('#modal'),b=$('#modalBody');if(!m||!b)return;b.innerHTML=`<div class="eyebrow">LOCAL PROFILE</div><h2>${esc(profile.display_name)}</h2><p>This copy of VEILED stores your profile and grimoire data only in this browser.</p><label style="display:grid;gap:6px">Display name<input id="localDisplayName" value="${esc(profile.display_name)}" maxlength="30"></label><div class="button-row" style="margin-top:14px"><button id="saveLocalProfile" class="primary-btn">Save</button><button id="exportVeiled" class="secondary-btn">Export Backup</button><label class="secondary-btn" style="cursor:pointer">Import Backup<input id="importVeiled" type="file" accept="application/json" hidden></label></div>`;m.classList.remove('hidden');$('#saveLocalProfile').onclick=()=>{profile.display_name=$('#localDisplayName').value.trim()||'VEILED Seeker';saveProfile();$('#accountChip').lastChild.textContent=profile.display_name;m.classList.add('hidden')};$('#exportVeiled').onclick=exportAll;$('#importVeiled').onchange=importAll}
function exportAll(){const data={version:1,exported_at:new Date().toISOString(),profile,settings,notes:get('veiledNotes',[]),xp:get('veiledXP',0),path:get('veiledPath',[]),altar:get('veiledAltar',[]),lastSigil:get('lastSigil',null),academy:get('veiledAcademyProgress',{}),witchProfile:get('veiledWitchProfile',{}),inbox:get('veiledOwnerInbox',[])};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`VEILED-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importAll(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.profile)set('veiledLocalProfile',d.profile);if(d.settings)set('veiledLocalSettings',d.settings);[['veiledNotes',d.notes],['veiledXP',d.xp],['veiledPath',d.path],['veiledAltar',d.altar],['lastSigil',d.lastSigil],['veiledAcademyProgress',d.academy],['veiledWitchProfile',d.witchProfile],['veiledOwnerInbox',d.inbox]].forEach(([k,v])=>{if(v!==undefined)set(k,v)});alert('VEILED backup imported. Reloading now.');location.reload()}catch{alert('That backup file could not be read.')}};r.readAsText(f)}
function applyFlags(){[['tarot','tarot_enabled'],['sigils','sigils_enabled'],['book','book_enabled']].forEach(([id,k])=>{const n=$(`.nav[data-page="${id}"]`);if(n)n.classList.toggle('disabled-feature',settings[k]===false)});$('#announcementBanner')?.remove();if(settings.announcement)$('.main')?.insertAdjacentHTML('afterbegin',`<div id="announcementBanner" class="announcement-banner">✦ ${esc(settings.announcement)}</div>`)}
function buildOwnerPanel(){if($('#ownerPanel'))return;$('.sidebar nav')?.insertAdjacentHTML('beforeend','<button class="nav" data-page="ownerPanel">⚙ <span>Owner Panel</span></button>');$('.main')?.insertAdjacentHTML('beforeend',`<section id="ownerPanel" class="page"><div class="section-head"><div><div class="eyebrow">LOCAL SITE CONTROL</div><h1>Owner Panel</h1><p>These controls affect only this browser because VEILED is running without a database.</p></div></div><div id="ownerPanelBody" class="owner-panel"></div></section>`);$('.nav[data-page="ownerPanel"]').onclick=()=>{$$('.page').forEach(p=>p.classList.toggle('active-page',p.id==='ownerPanel'));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page==='ownerPanel'));$('#pageTitle').textContent='Owner Panel';renderOwnerPanel()}}
function renderOwnerPanel(){const b=$('#ownerPanelBody');if(!b)return;b.innerHTML=`<div class="owner-grid"><div class="owner-card"><h3>Local Controls</h3><label class="owner-toggle"><span>Maintenance Mode</span><input id="setMaint" type="checkbox" ${settings.maintenance_mode?'checked':''}></label><label class="owner-toggle"><span>Tarot Enabled</span><input id="setTarot" type="checkbox" ${settings.tarot_enabled?'checked':''}></label><label class="owner-toggle"><span>Sigil Workshop Enabled</span><input id="setSigils" type="checkbox" ${settings.sigils_enabled?'checked':''}></label><label class="owner-toggle"><span>Book of Shadows Enabled</span><input id="setBook" type="checkbox" ${settings.book_enabled?'checked':''}></label></div><div class="owner-card"><h3>Announcement</h3><textarea id="setAnnouncement" class="owner-textarea">${esc(settings.announcement||'')}</textarea><label>Maintenance message</label><textarea id="setMaintMsg" class="owner-textarea">${esc(settings.maintenance_message||'')}</textarea><button id="saveSettings" class="primary-btn">Save Local Settings</button></div></div><div class="owner-card" style="margin-top:16px"><h3>Data</h3><p>Use backups if you clear browser data or move to another device.</p><button id="ownerExport" class="secondary-btn">Export VEILED Backup</button></div>`;$('#saveSettings').onclick=()=>{settings={...settings,maintenance_mode:$('#setMaint').checked,tarot_enabled:$('#setTarot').checked,sigils_enabled:$('#setSigils').checked,book_enabled:$('#setBook').checked,announcement:$('#setAnnouncement').value,maintenance_message:$('#setMaintMsg').value};saveSettings();applyFlags();alert('Local VEILED settings saved.')};$('#ownerExport').onclick=exportAll}
function start(){const btn=$('#openVeil');if(gateOpened())showSite();else if(btn)btn.addEventListener('click',()=>setTimeout(showSite,720));}
window.VEILED_LOCAL={get,set,get profile(){return profile},get settings(){return settings},saveProfile:()=>saveProfile(),saveSettings:()=>saveSettings(),exportAll};
start();
})();